### ISSUE TITLE
Upcoming Features

### ISSUE THREAD

**Issue by Myth0000** [Myth0000/First_Application#2]
Make it so when you have a name selected, it shows their Social Security number above.

**Comment by Myth0000** [comment]
Make ToolTip show their mother's maiden name.

**Comment by Myth0000** [comment]
color name according to gender

**Comment by Myth0000** [comment]
Save names so it pops up the next time you open the program

**Comment by Myth0000** [comment]
Create a list of people, sort them by net-worth, and have an option to say: "Apple needs a blood transfusion. They can take blood from Zombie. Would you like to confirm this action?"

**Comment by Myth0000** [comment]
Get a list of random first/last names so you can populate random FullNames when you add a new contact

**Comment by Myth0000** [comment]
NetWorth could be in the DisplayMemberPath so it's easier to determine a person's value.

**Comment by OrganizationUsername** [comment]
Close this one. Too many features to work on at once.
